project_id = "mbalhtajoruhzhraxnxc"

[functions.send-connection-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.reset-password-otp]
verify_jwt = false

[functions.send-verification-code]
verify_jwt = false
